config/routes.rb
Rails.application.routes.draw do
  get 'welcome/sign_in'
  get 'welcome/sign_up'
  get 'users/show'
  get 'users/search'
  get 'users/friends'
  get 'users/about'
  get 'users/photos'
  get 'my_profiles/requests'
  get 'my_profiles/friends'
  get 'my_profiles/about'
  get 'my_profiles/photos'
  get 'my_profiles/timeline'
  get 'my_profiles/avatar_info'
  post 'my_profiles/change_avatar'
  
  resource :my_profile

  resources :posts do
    resources  :comments
  end
  resources :posts do
    resources :likes
  end

  resources :comments do
    resources :likes
  end
  
  resources :friendships
  devise_for :users

  root 'my_profiles#timeline'
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/comment.rb
class Comment < ApplicationRecord
  belongs_to :user
  belongs_to :post
  has_many :likes, as: :likable, dependent: :destroy
  validates :content, presence: true
end

app/models/friendship.rb
class Friendship < ApplicationRecord
  belongs_to :user
  belongs_to :friend, class_name: :User
end

app/models/like.rb
class Like < ApplicationRecord
  belongs_to :user
  belongs_to :likable, polymorphic: true
end

app/models/post.rb
class Post < ApplicationRecord
  belongs_to :user
  has_many :comments, dependent: :destroy
  has_many :likes, as: :likable, dependent: :destroy
  has_one_attached :image
  validates :content, presence: true
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable, :confirmable
  has_many :posts, dependent: :destroy
  has_many :comments, dependent: :destroy
  has_many :likes, dependent: :destroy

  has_many :friendships
  has_many :friends, through: :friendships
  
  has_many :inverse_friendships, class_name: 'Friendship', foreign_key: 'friend_id'
  has_many :inverse_friends, through: :inverse_friendships, source: :user

  has_one_attached :avatar

  scope :search_by_first_name, ->(first_name) { where('first_name LIKE ?', "%#{first_name}%") }

  def find_like(likable)
    likes.find_by(likable_id: likable.id, likable_type: likable.class.name)
  end

  def find_friendship(friend)
    friendships.find_by(friend_id: friend.id)
  end

  def get_avatar
    if self.avatar.attached?
        image_tag self.avatar
    else
        image_tag 'profile_pics/profile_pic.png'
    end
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
  before_action :configure_permitted_parameters, if: :devise_controller?

  protected

  def configure_permitted_parameters
    devise_parameter_sanitizer.permit(:sign_up) { |u| u.permit(:first_name, :last_name, :email, :password, :sex) }
    devise_parameter_sanitizer.permit(:account_update) { |u| u.permit(:first_name, :last_name, :email, :password, :sex, :current_password) }
  end
end

app/controllers/comments_controller.rb
class CommentsController < ApplicationController
  before_action :authenticate_user!, :find_post

  def create
    @comment = @post.comments.build(comment_params.merge(user_id: current_user.id))
    respond_to do |format|
      @comment.save ? format.js : format.js { render :create_alert }
    end
  end

  def index
    @comments = @post.comments
    respond_to do |format|
      format.js
    end
  end

  def destroy
    @comments = @post.comments
    @comment = @comments.find(params[:id])
    respond_to do |format|
      @comment.destroy ? format.js : format.js { render :destroy_alert }
    end
  end

  private

  def comment_params
    params.require(:comment).permit(:content)
  end

  def find_post
    unless @post = Post.find_by_id(params[:post_id])
      flash[:notice] = 'Post not found'
      render layout: false
    end
  end
end

app/controllers/friendships_controller.rb
class FriendshipsController < ApplicationController
  before_action :authenticate_user!, :find_friendship, only: [:destroy, :update]

  def create
    @friendship = current_user.friendships.create(friend_id: params[:friend_id], status: 0)
    if @friendship.save
      redirect_back(fallback_location: root_path)
    end
  end

  def destroy
    if (@friendship.user_id == current_user.id) || (@friendship.friend_id == current_user.id)
      if @friendship.destroy
        redirect_back(fallback_location: root_path)
      end
    end
  end

  def update
    if @friendship.friend_id == current_user.id
      if @friendship.update_attribute(:status, 1)
        redirect_back(fallback_location: root_path)
      end
    end
  end

  private

  def find_friendship
    unless @friendship = Friendship.find_by(id: params[:id])
      render layout: false
    end
  end
end

app/controllers/home_controller.rb
class HomeController < ApplicationController
  before_action :find_user, only: [:about, :friends, :photos, :show]

  def index
    redirect_to welcome_sign_in_path unless user_signed_in?
  end

  def search
    @users =
      if params[:friend]
        User.search_by_first_name(params[:friend])
      else
        User.all
      end
  end

  def about
  end

  def friends
    friends = @user.friends.where('friendships.status = ?', 1)
    @friends = friends + @user.inverse_friends.where('friendships.status = ?', 1)
  end

  def photos
  end

  def requests
    @requests = current_user.inverse_friends.where('friendships.status = ?', 0)
  end

  def show
  end

  private

  def find_user
    unless @user = User.find_by_id(params[:user_id])
      flash[:notice] = 'User not found'
      render layout: false
    end
  end
end

app/controllers/likes_controller.rb
class LikesController < ApplicationController
  before_action :authenticate_user!, :set_up_likable

  def create
    @like = @likable.likes.build(user_id: current_user.id)
    respond_to do |format|
      @like.save ? format.js : format.js { render :create_alert }
    end
  end

  def destroy
    @like = @likable.likes.find(params[:id])
    respond_to do |format|
      @like.destroy ? format.js : format.js { render :destroy_alert }
    end
  end

  private

  def set_up_likable
    unless (@likable =
      if params[:post_id]
        Post.find(params[:post_id])
      else
        Comment.find(params[:comment_id])
      end)
      flash[:notice] = 'Not found'
      render layout: false
    end
  end
end

app/controllers/posts_controller.rb
class PostsController < ApplicationController
  before_action :authenticate_user!

  def new
    @post = current_user.posts.build
  end

  def create
    # respond_with Post.create(post_params.merge(user_id: current_user.id))
    @post = current_user.posts.build(post_params)
    @post.image.attach(params[:post][:image])
    respond_to do |format|
      if @post.save
        format.js
        format.html { redirect_to root_path }
      else
        format.js { render 'create_alert' }
      end
    end
  end

  def destroy
    @post = current_user.posts.find(params[:id])
    if @post.destroy
      redirect_back(fallback_location: root_path)
    end
  end

  private

  def post_params
    params.require(:post).permit(:content)
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  before_action :find_user, only: [:about, :friends, :photos, :show]

  def search
    @users =
      if params[:friend]
        User.search_by_first_name(params[:friend])
      else
        User.all
      end
  end

  def about
  end

  def friends
    friends = @user.friends.where('friendships.status = ?', 1)
    @friends = friends + @user.inverse_friends.where('friendships.status = ?', 1)
  end

  def photos
  end

  def show
  end

  private

  def find_user
    unless @user = User.find_by_id(params[:user_id])
      flash[:notice] = 'User not found'
      render layout: false
    end
  end
end

app/controllers/welcome_controller.rb
class WelcomeController < ApplicationController
  def sign_in
  end

  def sign_up
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/comments_helper.rb
module CommentsHelper
end

app/helpers/friendships_helper.rb
module FriendshipsHelper
end

app/helpers/likes_helper.rb
module LikesHelper
end

app/helpers/my_profiles_helper.rb
module MyProfilesHelper
end

app/helpers/posts_helper.rb
module PostsHelper
end

app/helpers/registrations_helper.rb
module RegistrationsHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/helpers/welcome_helper.rb
module WelcomeHelper
end

app/views/comments/_comment.html.erb
<p>
  <b>
    <em>
      <%= "#{comment.user.first_name} #{comment.user.last_name}" %>
    </em>
  </b>
  <%= comment.content %><br>
  <span id = "like<%= comment.id %>">
    <%= render( partial: 'comments/comment_like', locals: {comment: comment})  %>
  </span> &nbsp; &nbsp; &nbsp;
  <% if (comment.user == current_user) || (comment.post == current_user) %>
    <%= link_to "Delete", post_comment_path(post_id: comment.post_id, id: comment.id), method: :delete, remote: true  %> &nbsp; &nbsp; &nbsp;
  <% end %>
  <%= time_ago_in_words(comment.created_at) %>
</p>

app/views/comments/_comment_like.html.erb
<% if current_user.find_like(comment) %>
  <b><%= link_to 'Like', comment_like_path(comment_id: comment.id, id: current_user.find_like(comment).id), method: :delete, remote: true %></b>
<% else %>
  <%= link_to 'Like', comment_likes_path(comment_id: comment.id), method: :post, remote: true %>
<% end %>

app/views/comments/create.js.erb
var com_box = $("#comments<%= @post.id %>");
com_box[0].style.display = "block";
com_box.append(" <%= j render(:partial => "comment",  :locals => {:comment => @comment}) %> ");

app/views/comments/create_alert.js.erb
alert( 'comment cannot be created' )

app/views/comments/destroy.js.erb
$("#comments<%= @post.id %>").html(" <%= j render partial: 'comment', collection: @comments, as: :comment %> ");

app/views/comments/destroy_alert.js.erb
alert( 'comment cannot be deleted' )

app/views/comments/index.js.erb
var com_box = $("#comments<%= @post.id %>");
if (com_box[0].style.display === "none") {
  com_box.html(" <%= j render partial: 'comment', collection: @comments, as: :comment %> ");
}
com_box.toggle();

app/views/friendships/create.html.erb
<div style="margin-top: 120px">
  cannot send request
</div>

app/views/friendships/destroy.html.erb
<div style="margin-top: 120px">
  cannot delete friendship
</div>

app/views/friendships/update.html.erb
<div style="margin-top: 120px">
  Unable to accept request
</div>

app/views/likes/create.js.erb
<% if @likable.class.name == "Post" %>
  $("#likes<%= @likable.id %>").html(" <%= j render(partial: 'posts/like', :locals => {:post => @likable}) %> ");
<% else %>
  $("#like<%= @likable.id %>").html(" <%= j render(partial: 'comments/comment_like', :locals => {:comment => @likable}) %> ");
<% end %>

app/views/likes/create_alert.js.erb
alert( 'cannot like' )

app/views/likes/destroy.js.erb
<% if @likable.class.name == "Post" %>
  $("#likes<%= @likable.id %>").html(" <%= j render(partial: 'posts/like', locals: {post: @likable}) %> ");
<% else %>
  $("#like<%= @likable.id %>").html(" <%= j render(partial: 'comments/comment_like', locals: {comment: @likable}) %> ");
<% end %>

app/views/likes/destroy_alert.js.erb
alert( 'cannot dislike' )

app/views/posts/_like.html.erb
<% if current_user.find_like(post) %>
  <%= link_to ' Like', post_like_path(post_id: post.id, id: current_user.find_like(post).id), method: :delete, remote: true, class: "fa fa-thumbs-up btn", style: "color:lightskyblue;" %>
<% else %>
  <%= link_to ' Like', post_likes_path(post_id: post.id), method: :post, remote: true, class: "fa fa-thumbs-up btn"%>
<% end %>

app/views/posts/_post.html.erb
<div class = "card" style = "width: 30rem;">
  <div class="card-header">
    <% if current_user==post.user %>
      <span style="float:right" class="dropdown">
        <button type="button" class="btn btn-default dropdown-toggle" data-toggle="dropdown"></button>
        <ul class="dropdown-menu">
          <li><%= link_to "Edit", "#", class: "dropdown-item" %></li>
          <li><%= link_to "Delete", post_path(post), method: :delete, class: "dropdown-item" %></li>
        </ul>
      </span>
    <% end %>
    <% if current_user == post.user %>
      <%= link_to "#{current_user.first_name} #{current_user.last_name}", my_profile_path %>
    <% else %>
      <%= link_to "#{post.user.first_name} #{post.user.last_name}", users_show_path(user_id: post.user.id) %>
    <% end %>
    <br>
    <%= time_ago_in_words(post.created_at) %><br>
  </div>
  <div class = "card-body">
    
      <%= post.content %><br>
      <% if post.image.attached? %>
        <%= image_tag post.image, style: "width:100%;" %>
      <% end %>
      
      <hr>
      <span id = <%= "likes#{post.id}" %> >
        <%= render(partial: 'posts/like', locals: {post: post}) %>
      </span>
      <span><%= link_to ' Comments', post_comments_path(post), remote: true, class: "fa fa-comment btn" %></span>
      <hr>
      
      <div id= <%= "comments#{post.id}" %> style="display:none" ></div>
      
      <div id= "add_comment" >
        <%= form_with(model: [ post, post.comments.build ], remote: true ) do |f| %>
          <%= f.text_field :content, placeholder: "Add a comment..", style: "width: 100%" %>
        <% end %>
      </div>
    
  </div>
</div>

app/views/posts/create.js.erb
$("#posts").prepend(" <li><%= j render(:partial => "home/post",  :locals => {:post => @post}) %></li> ");

app/views/posts/create_alert.js.erb
alert ( 'cannot create post' );

app/views/posts/destroy.html.erb
<div style="margin-top: 120px">
  cannot delete post
</div>