config/routes.rb
Rails.application.routes.draw do
  get 'welcome/sign_in'
  get 'welcome/sign_up'
  get 'users/show'
  get 'users/search'
  get 'users/friends'
  get 'users/about'
  get 'users/photos'
  get 'my_profiles/requests'
  get 'my_profiles/friends'
  get 'my_profiles/about'
  get 'my_profiles/photos'
  get 'my_profiles/timeline'
  get 'my_profiles/avatar_info'
  post 'my_profiles/change_avatar'
  
  resource :my_profile

  resources :posts do
    resources  :comments
  end
  resources :posts do
    resources :likes
  end

  resources :comments do
    resources :likes
  end
  
  resources :friendships
  devise_for :users

  root 'my_profiles#timeline'
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable, :confirmable
  has_many :posts, dependent: :destroy
  has_many :comments, dependent: :destroy
  has_many :likes, dependent: :destroy

  has_many :friendships
  has_many :friends, through: :friendships
  
  has_many :inverse_friendships, class_name: 'Friendship', foreign_key: 'friend_id'
  has_many :inverse_friends, through: :inverse_friendships, source: :user

  has_one_attached :avatar

  scope :search_by_first_name, ->(first_name) { where('first_name LIKE ?', "%#{first_name}%") }

  def find_like(likable)
    likes.find_by(likable_id: likable.id, likable_type: likable.class.name)
  end

  def find_friendship(friend)
    friendships.find_by(friend_id: friend.id)
  end

  def get_avatar
    if self.avatar.attached?
        image_tag self.avatar
    else
        image_tag 'profile_pics/profile_pic.png'
    end
  end
end

app/controllers/users/confirmations_controller.rb
# frozen_string_literal: true

class Users::ConfirmationsController < Devise::ConfirmationsController
  # GET /resource/confirmation/new
  # def new
  #   super
  # end

  # POST /resource/confirmation
  # def create
  #   super
  # end

  # GET /resource/confirmation?confirmation_token=abcdef
  # def show
  #   super
  # end

  # protected

  # The path used after resending confirmation instructions.
  # def after_resending_confirmation_instructions_path_for(resource_name)
  #   super(resource_name)
  # end

  # The path used after confirmation.
  # def after_confirmation_path_for(resource_name, resource)
  #   super(resource_name, resource)
  # end
end

app/controllers/users/omniauth_callbacks_controller.rb
# frozen_string_literal: true

class Users::OmniauthCallbacksController < Devise::OmniauthCallbacksController
  # You should configure your model like this:
  # devise :omniauthable, omniauth_providers: [:twitter]

  # You should also create an action method in this controller like this:
  # def twitter
  # end

  # More info at:
  # https://github.com/plataformatec/devise#omniauth

  # GET|POST /resource/auth/twitter
  # def passthru
  #   super
  # end

  # GET|POST /users/auth/twitter/callback
  # def failure
  #   super
  # end

  # protected

  # The path used when OmniAuth fails
  # def after_omniauth_failure_path_for(scope)
  #   super(scope)
  # end
end

app/controllers/users/passwords_controller.rb
# frozen_string_literal: true

class Users::PasswordsController < Devise::PasswordsController
  # GET /resource/password/new
  # def new
  #   super
  # end

  # POST /resource/password
  # def create
  #   super
  # end

  # GET /resource/password/edit?reset_password_token=abcdef
  # def edit
  #   super
  # end

  # PUT /resource/password
  # def update
  #   super
  # end

  # protected

  # def after_resetting_password_path_for(resource)
  #   super(resource)
  # end

  # The path used after sending reset password instructions
  # def after_sending_reset_password_instructions_path_for(resource_name)
  #   super(resource_name)
  # end
end

app/controllers/users/registrations_controller.rb
# frozen_string_literal: true

class Users::RegistrationsController < Devise::RegistrationsController
  # before_action :configure_sign_up_params, only: [:create]
  # before_action :configure_account_update_params, only: [:update]

  # GET /resource/sign_up
  # def new
  #   super
  # end

  # POST /resource
  # def create
  #   super
  # end

  # GET /resource/edit
  # def edit
  #   super
  # end

  # PUT /resource
  # def update
  #   super
  # end

  # DELETE /resource
  # def destroy
  #   super
  # end

  # GET /resource/cancel
  # Forces the session data which is usually expired after sign
  # in to be expired now. This is useful if the user wants to
  # cancel oauth signing in/up in the middle of the process,
  # removing all OAuth session data.
  # def cancel
  #   super
  # end

  # protected

  # If you have extra params to permit, append them to the sanitizer.
  # def configure_sign_up_params
  #   devise_parameter_sanitizer.permit(:sign_up, keys: [:attribute])
  # end

  # If you have extra params to permit, append them to the sanitizer.
  # def configure_account_update_params
  #   devise_parameter_sanitizer.permit(:account_update, keys: [:attribute])
  # end

  # The path used after sign up.
  # def after_sign_up_path_for(resource)
  #   super(resource)
  # end

  # The path used after sign up for inactive accounts.
  # def after_inactive_sign_up_path_for(resource)
  #   super(resource)
  # end
end

app/controllers/users/sessions_controller.rb
# frozen_string_literal: true

class Users::SessionsController < Devise::SessionsController
  # before_action :configure_sign_in_params, only: [:create]

  # GET /resource/sign_in
  # def new
  #   super
  # end

  # POST /resource/sign_in
  # def create
  #   super
  # end

  # DELETE /resource/sign_out
  # def destroy
  #   super
  # end

  # protected

  # If you have extra params to permit, append them to the sanitizer.
  # def configure_sign_in_params
  #   devise_parameter_sanitizer.permit(:sign_in, keys: [:attribute])
  # end
end

app/controllers/users/unlocks_controller.rb
# frozen_string_literal: true

class Users::UnlocksController < Devise::UnlocksController
  # GET /resource/unlock/new
  # def new
  #   super
  # end

  # POST /resource/unlock
  # def create
  #   super
  # end

  # GET /resource/unlock?unlock_token=abcdef
  # def show
  #   super
  # end

  # protected

  # The path used after sending unlock password instructions
  # def after_sending_unlock_instructions_path_for(resource)
  #   super(resource)
  # end

  # The path used after unlocking the resource
  # def after_unlock_path_for(resource)
  #   super(resource)
  # end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  before_action :find_user, only: [:about, :friends, :photos, :show]

  def search
    @users =
      if params[:friend]
        User.search_by_first_name(params[:friend])
      else
        User.all
      end
  end

  def about
  end

  def friends
    friends = @user.friends.where('friendships.status = ?', 1)
    @friends = friends + @user.inverse_friends.where('friendships.status = ?', 1)
  end

  def photos
  end

  def show
  end

  private

  def find_user
    unless @user = User.find_by_id(params[:user_id])
      flash[:notice] = 'User not found'
      render layout: false
    end
  end
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/users/_friendship.html.erb
<% if (current_user.find_friendship(user) && (current_user.find_friendship(user).status == 1)) %>
  <%= link_to ' Friend', friendship_path(id: current_user.find_friendship(user).id), method: :delete, class: "fa fa-check" %>
<% elsif (user.find_friendship(current_user) && (user.find_friendship(current_user).status == 1)) %>
  <%= link_to ' Friend', friendship_path(id: user.find_friendship(current_user).id), method: :delete, class: "fa fa-check" %>
<% elsif current_user.find_friendship(user) %>
  <%= link_to 'Requested', friendship_path(id: current_user.find_friendship(user).id), method: :delete %>
<% elsif user.find_friendship(current_user) %>
  <%= link_to 'Confirm Request', friendship_path(id: user.find_friendship(current_user).id), method: :patch %>
<% elsif user != current_user %>
  <%= link_to 'Add Friend', friendships_path(friend_id: user), method: :post %>
<% end %>

app/views/users/_top.html.erb
<div class="row" style="margin-top: 120px">
  <span class="col-sm-2"></span>
  <div class="col-sm-3">
    <b><%= "#{user.first_name} #{user.last_name}" %></b>
  </div>
  <div class="col-sm-4">
    <% if current_user==user %>
      <button class="btn btn-primary">Update Profile</button>
    <% else %>
      <%= render(partial: 'friendship', locals:{user: user}) %>
      <button class="btn btn-primary">Message</button>
    <% end %>
  </div>
</div>
<br>

<nav class="navbar navbar-expand-lg navbar-dark bg-dark">
  <div class="container-fluid">
    <div>
      <ul class="nav navbar-nav mr-auto" style="flex-direction: row;">
        <li><a class="nav-item nav-link" href="show?user_id=<%= user.id %>">Timeline</a></li>
        <li><a class="nav-item nav-link" href="about?user_id=<%= user.id %>">About</a></li>
        <li><a class="nav-item nav-link" href="friends?user_id=<%= user.id %>">Friends</a></li>
        <li><a class="nav-item nav-link" href="photos?user_id=<%= user.id %>">Photos</a></li>
      </ul>
    </div>
  </div>
</nav>
<br>

app/views/users/about.html.erb
<%= render(partial: 'top', locals: {user: @user}) %>

app/views/users/friends.html.erb
<%= render(partial: 'top', locals: {user: @user}) %>

<div class="row">
  <span class="col-md-1"></span>
  <div id="main" class="col-md-4">
    <ul id="body" type="none">
      <% @friends.each do |f| %>
        <div class="row">
          <div class="col-md-5">
            <%= link_to "#{f.first_name} #{f.last_name}", users_show_path(user_id: f.id) %>
          </div>
            <div class="col-md-4">
              <%= render(partial: 'friendship', locals:{user: f}) %>
            </div></li>
        </div>
        <hr>
      <% end %>
    </ul>
  </div>
</div>

app/views/users/photos.html.erb
<%= render(partial: 'top', locals: {user: @user}) %>

app/views/users/search.html.erb
<div class="row" style="margin-top: 120px">
  <span class="col-md-1"></span>
  <div id="main" class="col-md-4">
    <ul id="body" type="none">
      <% @users.each do |user| %>
        <div class="row">
          <div class="col-md-5">
            <%= link_to "#{user.first_name} #{user.last_name}", users_show_path(user_id: user.id) %>
          </div>
          <div class="col-md-4">
            <%= render(partial: 'friendship', locals:{user: user}) %>
          </div></li>
        </div>
        <hr>
      <% end %>
    </ul>
  </div>
</div>

app/views/users/show.html.erb
<%= render(partial: 'top', locals: {user: @user}) %>

<div id="main">
  <ul id="body" type="none">
    <div id = "posts" class="panel panel-default" style = "margin-left: 20rem; width: 30rem;">
      <% if @user.posts.empty? %>
        No Posts to show
      <% else %>
        <% @user.posts.each do |post| %>
          <li>
            <%= render(partial: 'posts/post',  :locals => {:post => post}) %>
          </li>
        <% end %>
      <% end %>
    </div>

  </ul>
</div>