config/routes.rb
Rails.application.routes.draw do
  get 'welcome/sign_in'
  get 'welcome/sign_up'
  get 'users/show'
  get 'users/search'
  get 'users/friends'
  get 'users/about'
  get 'users/photos'
  get 'my_profiles/requests'
  get 'my_profiles/friends'
  get 'my_profiles/about'
  get 'my_profiles/photos'
  get 'my_profiles/timeline'
  get 'my_profiles/avatar_info'
  post 'my_profiles/change_avatar'
  
  resource :my_profile

  resources :posts do
    resources  :comments
  end
  resources :posts do
    resources :likes
  end

  resources :comments do
    resources :likes
  end
  
  resources :friendships
  devise_for :users

  root 'my_profiles#timeline'
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/comment.rb
class Comment < ApplicationRecord
  belongs_to :user
  belongs_to :post
  has_many :likes, as: :likable, dependent: :destroy
  validates :content, presence: true
end

app/models/friendship.rb
class Friendship < ApplicationRecord
  belongs_to :user
  belongs_to :friend, class_name: :User
end

app/models/like.rb
class Like < ApplicationRecord
  belongs_to :user
  belongs_to :likable, polymorphic: true
end

app/models/post.rb
class Post < ApplicationRecord
  belongs_to :user
  has_many :comments, dependent: :destroy
  has_many :likes, as: :likable, dependent: :destroy
  has_one_attached :image
  validates :content, presence: true
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable, :confirmable
  has_many :posts, dependent: :destroy
  has_many :comments, dependent: :destroy
  has_many :likes, dependent: :destroy

  has_many :friendships
  has_many :friends, through: :friendships
  
  has_many :inverse_friendships, class_name: 'Friendship', foreign_key: 'friend_id'
  has_many :inverse_friends, through: :inverse_friendships, source: :user

  has_one_attached :avatar

  scope :search_by_first_name, ->(first_name) { where('first_name LIKE ?', "%#{first_name}%") }

  def find_like(likable)
    likes.find_by(likable_id: likable.id, likable_type: likable.class.name)
  end

  def find_friendship(friend)
    friendships.find_by(friend_id: friend.id)
  end

  def get_avatar
    if self.avatar.attached?
        image_tag self.avatar
    else
        image_tag 'profile_pics/profile_pic.png'
    end
  end
end

app/controllers/comments_controller.rb
class CommentsController < ApplicationController
  before_action :authenticate_user!, :find_post

  def create
    @comment = @post.comments.build(comment_params.merge(user_id: current_user.id))
    respond_to do |format|
      @comment.save ? format.js : format.js { render :create_alert }
    end
  end

  def index
    @comments = @post.comments
    respond_to do |format|
      format.js
    end
  end

  def destroy
    @comments = @post.comments
    @comment = @comments.find(params[:id])
    respond_to do |format|
      @comment.destroy ? format.js : format.js { render :destroy_alert }
    end
  end

  private

  def comment_params
    params.require(:comment).permit(:content)
  end

  def find_post
    unless @post = Post.find_by_id(params[:post_id])
      flash[:notice] = 'Post not found'
      render layout: false
    end
  end
end

app/controllers/home_controller.rb
class HomeController < ApplicationController
  before_action :find_user, only: [:about, :friends, :photos, :show]

  def index
    redirect_to welcome_sign_in_path unless user_signed_in?
  end

  def search
    @users =
      if params[:friend]
        User.search_by_first_name(params[:friend])
      else
        User.all
      end
  end

  def about
  end

  def friends
    friends = @user.friends.where('friendships.status = ?', 1)
    @friends = friends + @user.inverse_friends.where('friendships.status = ?', 1)
  end

  def photos
  end

  def requests
    @requests = current_user.inverse_friends.where('friendships.status = ?', 0)
  end

  def show
  end

  private

  def find_user
    unless @user = User.find_by_id(params[:user_id])
      flash[:notice] = 'User not found'
      render layout: false
    end
  end
end

app/controllers/likes_controller.rb
class LikesController < ApplicationController
  before_action :authenticate_user!, :set_up_likable

  def create
    @like = @likable.likes.build(user_id: current_user.id)
    respond_to do |format|
      @like.save ? format.js : format.js { render :create_alert }
    end
  end

  def destroy
    @like = @likable.likes.find(params[:id])
    respond_to do |format|
      @like.destroy ? format.js : format.js { render :destroy_alert }
    end
  end

  private

  def set_up_likable
    unless (@likable =
      if params[:post_id]
        Post.find(params[:post_id])
      else
        Comment.find(params[:comment_id])
      end)
      flash[:notice] = 'Not found'
      render layout: false
    end
  end
end

app/controllers/my_profiles_controller.rb
class MyProfilesController < ApplicationController
  def show
  end

  def edit
  end

  def requests
    @requests = current_user.inverse_friends.where('friendships.status = ?', 0)
  end

  def timeline
    if user_signed_in?
      @posts = Post.order('created_at DESC').where("user_id != #{current_user.id}").page(params[:page]).per(5)
    else
      redirect_to welcome_sign_in_path
    end
  end

  def about
  end

  def friends
    friends = current_user.friends.where('friendships.status = ?', 1)
    @friends = friends + current_user.inverse_friends.where('friendships.status = ?', 1)
  end

  def photos
  end

  def avatar_info
  end

  def change_avatar
    current_user.avatar.attach(params[:user][:avatar])
    redirect_back(fallback_location: root_path)
  end
end

app/controllers/posts_controller.rb
class PostsController < ApplicationController
  before_action :authenticate_user!

  def new
    @post = current_user.posts.build
  end

  def create
    # respond_with Post.create(post_params.merge(user_id: current_user.id))
    @post = current_user.posts.build(post_params)
    @post.image.attach(params[:post][:image])
    respond_to do |format|
      if @post.save
        format.js
        format.html { redirect_to root_path }
      else
        format.js { render 'create_alert' }
      end
    end
  end

  def destroy
    @post = current_user.posts.find(params[:id])
    if @post.destroy
      redirect_back(fallback_location: root_path)
    end
  end

  private

  def post_params
    params.require(:post).permit(:content)
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  before_action :find_user, only: [:about, :friends, :photos, :show]

  def search
    @users =
      if params[:friend]
        User.search_by_first_name(params[:friend])
      else
        User.all
      end
  end

  def about
  end

  def friends
    friends = @user.friends.where('friendships.status = ?', 1)
    @friends = friends + @user.inverse_friends.where('friendships.status = ?', 1)
  end

  def photos
  end

  def show
  end

  private

  def find_user
    unless @user = User.find_by_id(params[:user_id])
      flash[:notice] = 'User not found'
      render layout: false
    end
  end
end

app/controllers/welcome_controller.rb
class WelcomeController < ApplicationController
  def sign_in
  end

  def sign_up
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/comments_helper.rb
module CommentsHelper
end

app/helpers/friendships_helper.rb
module FriendshipsHelper
end

app/helpers/likes_helper.rb
module LikesHelper
end

app/helpers/my_profiles_helper.rb
module MyProfilesHelper
end

app/helpers/posts_helper.rb
module PostsHelper
end

app/helpers/registrations_helper.rb
module RegistrationsHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/helpers/welcome_helper.rb
module WelcomeHelper
end

app/views/my_profiles/_email_section.html.erb
<%= form_for(current_user, as: :user, url: registration_path(:user), html: { method: :patch }) do |f| %>

  <div class="field row">
    <%= f.label 'Name:', class: "col-sm-2" %>
    <%= f.text_field :first_name %><%= f.text_field :last_name %>
  </div>
  <br>

  <div class="field row">
    <%= f.label 'Email: ', class: "col-sm-2" %><br />
    <%= f.email_field :email, autofocus: true, autocomplete: "email" %>
  </div>

  <% if Devise.mappings[:user].confirmable? && current_user.pending_reconfirmation? %>
    <div>Currently waiting confirmation for: <%= current_user.unconfirmed_email %></div>
  <% end %>
  <br>

  <div class="field row">
    <div class="col-sm-6"><%= f.label :new_password %> <i>(You can leave it blank)</i></div>
    <%= f.password_field :password, autocomplete: "new-password" %>
    <% if @minimum_password_length %>
      <br />
      <em><%= @minimum_password_length %> characters minimum</em>
    <% end %>
  </div>
  <br>

  <div class="field row">
    <%= f.label :password_confirmation, class: "col-sm-6" %><br />
    <%= f.password_field :password_confirmation, autocomplete: "new-password" %>
  </div>
  <br>

  <div class="field row">
    <%= f.label :current_password, class: "col-sm-6" %>
    <%= f.password_field :current_password, autocomplete: "current-password" %>
  </div>
  <br>

  <div class="actions">
    <%= f.submit "Change", class: "btn-info" %>
  </div>
<% end %>

app/views/my_profiles/_picture.html.erb
<% if current_user.avatar.attached? %>
<%= image_tag current_user.avatar, style: "width: 100px; height: 100px" %>
<% else %>
<%= image_tag 'profile_pics/profile_pic.png', style: "width: 100px; height: 100px" %>
<% end %>
<%= form_with scope: :user,url: my_profiles_change_avatar_path do |form| %>
  <p>
    <%= form.file_field :avatar %>
  </p>

  <p>
    <%= form.submit :Change , class: "btn btn-success" %>
  </p>
<% end %>

app/views/my_profiles/_request.html.erb
<li>
  <div class = "row">
    <span class="col-sm-4"><%= "#{request.first_name} #{request.last_name}" %></span>
    <span class="col-sm-4"><%= link_to 'Confirm', friendship_path(id: request.find_friendship(current_user).id), method: :patch %> </li></span>
 </div>
</li>
<li> <hr> </li>

app/views/my_profiles/_top.html.erb
<div class="row" style="margin-top: 120px">
  <span class="col-sm-1"></span>
  <% if current_user.avatar.attached? %>
    <%= image_tag current_user.avatar, style: "width: 100px; height: 100px; border-radius: 50%" %>
  <% else %>
    <%= image_tag 'profile_pics/profile_pic.png', style: "width: 100px; height: 100px" %>
  <% end %>
  <div class="col-sm-3">
    <b><%= "#{current_user.first_name} #{current_user.last_name}" %></b>
  </div>
</div>
<br>

<nav class="navbar navbar-expand-lg navbar-dark bg-dark">
  <div class="container-fluid">
    <div>
      <ul class="nav navbar-nav mr-auto" style="flex-direction: row;">
        <li><a class="nav-item nav-link" href="/my_profile">Timeline</a></li>
        <li><a class="nav-item nav-link" href="/my_profiles/about">About</a></li>
        <li><a class="nav-item nav-link" href="/my_profiles/friends">Friends</a></li>
        <li><a class="nav-item nav-link" href="/my_profiles/photos">Photos</a></li>
      </ul>
    </div>
  </div>
</nav>
<br>

app/views/my_profiles/about.html.erb
<%= render 'top' %>

<div class="nav flex-column" style="float:left">
  <a href="/my_profiles/about" class="nav-item nav-link">Email and Password:</a>
  <%= link_to 'Profile Picture:', "/my_profiles/avatar_info", class: "nav-item nav-link", remote: true %>
</div>

<div id="main" class="card" style="width:50%">
  <div id="my_info" class="card-body">
    <%= render 'email_section' %>
  </div>
</div>
<br>

<div class="row">
  <span class="col-sm-2"></span>
  <span class="col-sm-4"><%= button_to "Delete my account", registration_path(:user), data: { confirm: "Are you sure?" }, method: :delete %></span>
</div>

app/views/my_profiles/avatar_info.js.erb
$("#my_info").html("<%= j render 'picture' %>");

app/views/my_profiles/friends.html.erb
<%= render 'top' %>

<div class="row">
  <span class="col-md-1"></span>
  <div id="main" class="col-md-4">
    <ul id="body" type="none">
      <% @friends.each do |f| %>
        <div class="row">
          <div class="col-md-5">

            <%= link_to "#{f.first_name} #{f.last_name}", users_show_path(user_id: f.id) %>
          </div>
            <div class="col-md-4">
              <% if current_user.find_friendship(f) %>
                <%= link_to ' Friend', friendship_path(id: current_user.find_friendship(f).id), method: :delete, class: "fa fa-check" %>
              <% else %>
                <%= link_to ' Friend', friendship_path(id: f.find_friendship(current_user).id), method: :delete, class: "fa fa-check" %>
              <% end %>
            </div>
        </div>
        <hr>
      <% end %>
    </ul>
  </div>
</div>

app/views/my_profiles/photos.html.erb
<%= render 'top' %>

app/views/my_profiles/requests.js.erb
<% if @requests.empty? %>
  $('#requests').html("No Friend Requests");
<% else %>
  $("#requests").html("<%= j render(partial: 'request', collection: @requests) %>");
<% end %>
$('#requests').dropdown('toggle');

app/views/my_profiles/show.html.erb
<%= render 'top' %>

<div id="main">
  <ul id="body" type="none">
    <div class = "card panel panel-default" style = "margin-left: 20rem; width: 30rem;">
      <div class = "card-body">
        <%= form_with scope: :post,url: posts_path do |form| %>
          <p>
            <%= form.text_field :content, placeholder: "share your wits.."%>
            <%= form.file_field :image %>
          </p>
     
          <p>
            <%= form.submit :Post , class: "btn btn-success" %>
          </p>
        <% end %>
      </div>
    </div>
    <div id = "posts" class="panel panel-default" style = "margin-left: 20rem; width: 30rem;">
      <% if current_user.posts.empty? %>
        No Posts to show
      <% else %>
        <% current_user.posts.each do |post| %>
          <li>
            <%= render(partial: 'posts/post',  :locals => {:post => post}) %>
          </li>
        <% end %>
      <% end %>
    </div>
  </ul>
</div>

app/views/my_profiles/timeline.html.erb
<div id="main" style="margin-top: 120px">
  <ul id="body" type="none">
    <div class = "card panel panel-default" style = "margin-left: 20rem; width: 30rem;">
      <div class = "card-body">
        <%= form_with scope: :post,url: posts_path do |form| %>
          <p>
            <%= form.text_field :content, placeholder: "share your wits.."%>
            <%= form.file_field :image %>
          </p>
     
          <p>
            <%= form.submit :Post , class: "btn btn-success" %>
          </p>
        <% end %>
      </div>
    </div>
    <div id = "posts" class="panel panel-default" style = "margin-left: 20rem; width: 30rem;">
      <% if @posts.empty? %>
        No Posts to show
      <% else %>
        <% @posts.each do |post| %>
          <li>
            <%= render(partial: 'posts/post',  :locals => {:post => post}) %>
          </li>
        <% end %>
        <%= paginate @posts, theme: 'twitter-bootstrap-3' %>
        <%= page_entries_info @posts %>
      <% end %>
    </div>

  </ul>
</div>