config/routes.rb
Rails.application.routes.draw do
  get 'welcome/sign_in'
  get 'welcome/sign_up'
  get 'users/show'
  get 'users/search'
  get 'users/friends'
  get 'users/about'
  get 'users/photos'
  get 'my_profiles/requests'
  get 'my_profiles/friends'
  get 'my_profiles/about'
  get 'my_profiles/photos'
  get 'my_profiles/timeline'
  get 'my_profiles/avatar_info'
  post 'my_profiles/change_avatar'
  
  resource :my_profile

  resources :posts do
    resources  :comments
  end
  resources :posts do
    resources :likes
  end

  resources :comments do
    resources :likes
  end
  
  resources :friendships
  devise_for :users

  root 'my_profiles#timeline'
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/comment.rb
class Comment < ApplicationRecord
  belongs_to :user
  belongs_to :post
  has_many :likes, as: :likable, dependent: :destroy
  validates :content, presence: true
end

app/models/friendship.rb
class Friendship < ApplicationRecord
  belongs_to :user
  belongs_to :friend, class_name: :User
end

app/models/like.rb
class Like < ApplicationRecord
  belongs_to :user
  belongs_to :likable, polymorphic: true
end

app/models/post.rb
class Post < ApplicationRecord
  belongs_to :user
  has_many :comments, dependent: :destroy
  has_many :likes, as: :likable, dependent: :destroy
  has_one_attached :image
  validates :content, presence: true
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable, :confirmable
  has_many :posts, dependent: :destroy
  has_many :comments, dependent: :destroy
  has_many :likes, dependent: :destroy

  has_many :friendships
  has_many :friends, through: :friendships
  
  has_many :inverse_friendships, class_name: 'Friendship', foreign_key: 'friend_id'
  has_many :inverse_friends, through: :inverse_friendships, source: :user

  has_one_attached :avatar

  scope :search_by_first_name, ->(first_name) { where('first_name LIKE ?', "%#{first_name}%") }

  def find_like(likable)
    likes.find_by(likable_id: likable.id, likable_type: likable.class.name)
  end

  def find_friendship(friend)
    friendships.find_by(friend_id: friend.id)
  end

  def get_avatar
    if self.avatar.attached?
        image_tag self.avatar
    else
        image_tag 'profile_pics/profile_pic.png'
    end
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
  before_action :configure_permitted_parameters, if: :devise_controller?

  protected

  def configure_permitted_parameters
    devise_parameter_sanitizer.permit(:sign_up) { |u| u.permit(:first_name, :last_name, :email, :password, :sex) }
    devise_parameter_sanitizer.permit(:account_update) { |u| u.permit(:first_name, :last_name, :email, :password, :sex, :current_password) }
  end
end

app/controllers/comments_controller.rb
class CommentsController < ApplicationController
  before_action :authenticate_user!, :find_post

  def create
    @comment = @post.comments.build(comment_params.merge(user_id: current_user.id))
    respond_to do |format|
      @comment.save ? format.js : format.js { render :create_alert }
    end
  end

  def index
    @comments = @post.comments
    respond_to do |format|
      format.js
    end
  end

  def destroy
    @comments = @post.comments
    @comment = @comments.find(params[:id])
    respond_to do |format|
      @comment.destroy ? format.js : format.js { render :destroy_alert }
    end
  end

  private

  def comment_params
    params.require(:comment).permit(:content)
  end

  def find_post
    unless @post = Post.find_by_id(params[:post_id])
      flash[:notice] = 'Post not found'
      render layout: false
    end
  end
end

app/controllers/home_controller.rb
class HomeController < ApplicationController
  before_action :find_user, only: [:about, :friends, :photos, :show]

  def index
    redirect_to welcome_sign_in_path unless user_signed_in?
  end

  def search
    @users =
      if params[:friend]
        User.search_by_first_name(params[:friend])
      else
        User.all
      end
  end

  def about
  end

  def friends
    friends = @user.friends.where('friendships.status = ?', 1)
    @friends = friends + @user.inverse_friends.where('friendships.status = ?', 1)
  end

  def photos
  end

  def requests
    @requests = current_user.inverse_friends.where('friendships.status = ?', 0)
  end

  def show
  end

  private

  def find_user
    unless @user = User.find_by_id(params[:user_id])
      flash[:notice] = 'User not found'
      render layout: false
    end
  end
end

app/controllers/likes_controller.rb
class LikesController < ApplicationController
  before_action :authenticate_user!, :set_up_likable

  def create
    @like = @likable.likes.build(user_id: current_user.id)
    respond_to do |format|
      @like.save ? format.js : format.js { render :create_alert }
    end
  end

  def destroy
    @like = @likable.likes.find(params[:id])
    respond_to do |format|
      @like.destroy ? format.js : format.js { render :destroy_alert }
    end
  end

  private

  def set_up_likable
    unless (@likable =
      if params[:post_id]
        Post.find(params[:post_id])
      else
        Comment.find(params[:comment_id])
      end)
      flash[:notice] = 'Not found'
      render layout: false
    end
  end
end

app/controllers/posts_controller.rb
class PostsController < ApplicationController
  before_action :authenticate_user!

  def new
    @post = current_user.posts.build
  end

  def create
    # respond_with Post.create(post_params.merge(user_id: current_user.id))
    @post = current_user.posts.build(post_params)
    @post.image.attach(params[:post][:image])
    respond_to do |format|
      if @post.save
        format.js
        format.html { redirect_to root_path }
      else
        format.js { render 'create_alert' }
      end
    end
  end

  def destroy
    @post = current_user.posts.find(params[:id])
    if @post.destroy
      redirect_back(fallback_location: root_path)
    end
  end

  private

  def post_params
    params.require(:post).permit(:content)
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  before_action :find_user, only: [:about, :friends, :photos, :show]

  def search
    @users =
      if params[:friend]
        User.search_by_first_name(params[:friend])
      else
        User.all
      end
  end

  def about
  end

  def friends
    friends = @user.friends.where('friendships.status = ?', 1)
    @friends = friends + @user.inverse_friends.where('friendships.status = ?', 1)
  end

  def photos
  end

  def show
  end

  private

  def find_user
    unless @user = User.find_by_id(params[:user_id])
      flash[:notice] = 'User not found'
      render layout: false
    end
  end
end

app/controllers/welcome_controller.rb
class WelcomeController < ApplicationController
  def sign_in
  end

  def sign_up
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/comments_helper.rb
module CommentsHelper
end

app/helpers/friendships_helper.rb
module FriendshipsHelper
end

app/helpers/likes_helper.rb
module LikesHelper
end

app/helpers/my_profiles_helper.rb
module MyProfilesHelper
end

app/helpers/posts_helper.rb
module PostsHelper
end

app/helpers/registrations_helper.rb
module RegistrationsHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/helpers/welcome_helper.rb
module WelcomeHelper
end

app/views/welcome/sign_in.html.erb
<h2> Log in </h2>

<%= form_for(User.new, as: :user, url: session_path(:user)) do |f| %>
  <div class="field">
    <%= f.label :email %><br />
    <%= f.email_field :email, autofocus: true, autocomplete: "email" %>
  </div>

  <div class="field">
    <%= f.label :password %><br />
    <%= f.password_field :password, autocomplete: "current-password" %>
  </div>

  <% if Devise.mappings[:user].rememberable? %>
    <div class="field">
      <%= f.check_box :remember_me %>
      <%= f.label :remember_me %>
    </div>
  <% end %>

  <div class="actions">
    <%= f.submit "Log in" %>
  </div>

  <%= link_to 'Sign Up', welcome_sign_up_path %>
<% end %>

app/views/welcome/sign_up.html.erb
<body style="background-image: url('/assets/science.jpg'); background-size: cover; color:#FFFFFF;">
<center>
<h2>Sign up</h2>

<%= form_for(User.new, as: :user, url: registration_path(:user)) do |f| %>
  <%= render "devise/shared/error_messages", resource: User.new %>

  <div class="field">
    <%= f.label :first_name %><br />
    <%= f.text_field :first_name %>
  </div>

  <div class="field">
    <%= f.label :last_name %><br />
    <%= f.text_field :last_name %>
  </div>  

  <div class="field">
    <%= f.label :email %><br />
    <%= f.email_field :email, autofocus: true, autocomplete: "email" %>
  </div>

  <div class="field">
    <%= f.label :password %>
    <% if @minimum_password_length %>
    <em>(<%= @minimum_password_length %> characters minimum)</em>
    <% end %><br />
    <%= f.password_field :password, autocomplete: "new-password" %>
  </div>

  <div class="field">
    <%= f.label :password_confirmation %><br />
    <%= f.password_field :password_confirmation, autocomplete: "new-password" %>
  </div>


  <span class="field">
    <%= f.radio_button :sex, 'M', checked: true %>
    <%= f.label :male %> 
  </span>

  <span class="field">
    <%= f.radio_button :sex, 'F' %>
    <%= f.label :female %>
  </span>

  <div class="actions">
    <%= f.submit "Sign up" %>
  </div>
<% end %>
</center>